/* Fetch user details */
export const REQUEST_USER_DETAIL = "REQUEST_USER_DETAIL";
export const RECEIVE_USER_DETAIL = "RECEIVE_USER_DETAIL";
export const FETCH_USER_DETAIL_FAIL = "FETCH_USER_DETAIL_FAIL";

/**
 * Table
 */
export const REQUEST_TABLE_LIST = "REQUEST_TABLE_LIST";
export const RECEIVE_TABLE_LIST = "RECEIVE_TABLE_LIST";
export const FETCH_TABLE_LIST_FAIL = "FETCH_TABLE_LIST_FAIL";
export const SET_TABLE_PAGE = "SET_TABLE_PAGE";
export const CLEAR_TABLE_LIST = "CLEAR_TABLE_LIST";

/* Setting List */
export const REQUEST_SETTINGS_LIST = "REQUEST_SETTINGS_LIST";
export const RECEIVE_SETTINGS_LIST = "RECEIVE_SETTINGS_LIST";
export const FETCH_SETTINGS_LIST_FAIL = "FETCH_SETTINGS_LIST_FAIL";
