/* Fetch user details */
export const REQUEST_RENTALS_DETAIL = "REQUEST_RENTALS_DETAIL";
export const RECEIVE_RENTALS_DETAIL = "RECEIVE_RENTALS_DETAIL";
export const FETCH_RENTALS_DETAIL_FAIL = "FETCH_RENTALS_DETAIL_FAIL";

export const REQUEST_CREATE_RENTALS = "REQUEST_CREATE_RENTALS";
export const RECEIVE_CREATE_RENTALS = "RECEIVE_CREATE_RENTALS";
export const RENTALS_CREATE_ERROR = "RENTALS_CREATE_ERROR";

export const REQUEST_DELETE_RENTALS = "REQUEST_DELETE_RENTALS";
export const RECEIVE_DELETE_RENTALS = "RECEIVE_DELETE_RENTALS";
export const RENTALS_DELETE_ERROR = "RENTALS_DELETE_ERROR";

export const REQUEST_UPDATE_RENTALS = "REQUEST_UPDATE_RENTALS";
export const RECEIVE_UPDATE_RENTALS = "RECEIVE_UPDATE_RENTALS";
export const RENTALS_UPDATE_ERROR = "RENTALS_UPDATE_ERROR";

export const APPLICATIONS_GENERAL_TAB = "General";
export const APPLICATIONS_LOANS_TAB = "Loans";
export const APPLICATIONS_PAYMENTS_TAB = "Payments";
