/* Fetch user details */
export const REQUEST_CUSTOMER_DETAIL = "REQUEST_CUSTOMER_DETAIL";
export const RECEIVE_CUSTOMER_DETAIL = "RECEIVE_CUSTOMER_DETAIL";
export const FETCH_CUSTOMER_DETAIL_FAIL = "FETCH_CUSTOMER_DETAIL_FAIL";

export const REQUEST_CREATE_CUSTOMER = "REQUEST_CREATE_CUSTOMER";
export const RECEIVE_CREATE_CUSTOMER = "RECEIVE_CREATE_CUSTOMER";
export const CUSTOMER_CREATE_ERROR = "CUSTOMER_CREATE_ERROR";

export const REQUEST_DELETE_CUSTOMER = "REQUEST_DELETE_CUSTOMER";
export const RECEIVE_DELETE_CUSTOMER = "RECEIVE_DELETE_CUSTOMER";
export const CUSTOMER_DELETE_ERROR = "CUSTOMER_DELETE_ERROR";

export const REQUEST_UPDATE_CUSTOMER = "REQUEST_UPDATE_CUSTOMER";
export const RECEIVE_UPDATE_CUSTOMER = "RECEIVE_UPDATE_CUSTOMER";
export const CUSTOMER_UPDATE_ERROR = "CUSTOMER_UPDATE_ERROR";


export const APPLICATIONS_GENERAL_TAB = "General";
export const APPLICATIONS_LOANS_TAB = "Loans";
export const APPLICATIONS_PAYMENTS_TAB = "Payments";
