/* Fetch user details */
export const REQUEST_PAYMENT_MODE_DETAIL = "REQUEST_PAYMENT_MODE_DETAIL";
export const RECEIVE_PAYMENT_MODE_DETAIL = "RECEIVE_PAYMENT_MODE_DETAIL";
export const FETCH_PAYMENT_MODE_DETAIL_FAIL = "FETCH_PAYMENT_MODE_DETAIL_FAIL";

export const REQUEST_CREATE_PAYMENT_MODE = "REQUEST_CREATE_PAYMENT_MODE";
export const RECEIVE_CREATE_PAYMENT_MODE = "RECEIVE_CREATE_PAYMENT_MODE";
export const PAYMENT_MODE_CREATE_ERROR = "PAYMENT_MODE_CREATE_ERROR";

export const REQUEST_DELETE_PAYMENT_MODE = "REQUEST_DELETE_PAYMENT_MODE";
export const RECEIVE_DELETE_PAYMENT_MODE = "RECEIVE_DELETE_PAYMENT_MODE";
export const PAYMENT_MODE_DELETE_ERROR = "PAYMENT_MODE_DELETE_ERROR";

export const REQUEST_UPDATE_PAYMENT_MODE = "REQUEST_UPDATE_PAYMENT_MODE";
export const RECEIVE_UPDATE_PAYMENT_MODE = "RECEIVE_UPDATE_PAYMENT_MODE";
export const PAYMENT_MODE_UPDATE_ERROR = "PAYMENT_MODE_UPDATE_ERROR";
