/* Fetch user details */
export const REQUEST_ROLE_DETAIL = "REQUEST_ROLE_DETAIL";
export const RECEIVE_ROLE_DETAIL = "RECEIVE_ROLE_DETAIL";
export const FETCH_ROLE_DETAIL_FAIL = "FETCH_ROLE_DETAIL_FAIL";

export const REQUEST_CREATE_ROLE = "REQUEST_CREATE_ROLE";
export const RECEIVE_CREATE_ROLE = "RECEIVE_CREATE_ROLE";
export const ROLE_CREATE_ERROR = "ROLE_CREATE_ERROR";

export const REQUEST_DELETE_ROLE = "REQUEST_DELETE_ROLE";
export const RECEIVE_DELETE_ROLE = "RECEIVE_DELETE_ROLE";
export const ROLE_DELETE_ERROR = "ROLE_DELETE_ERROR";

export const REQUEST_UPDATE_ROLE = "REQUEST_UPDATE_ROLE";
export const RECEIVE_UPDATE_ROLE = "RECEIVE_UPDATE_ROLE";
export const ROLE_UPDATE_ERROR = "ROLE_UPDATE_ERROR";
