/* Fetch user details */
export const REQUEST_VEHICLES_DETAIL = "REQUEST_VEHICLES_DETAIL";
export const RECEIVE_VEHICLES_DETAIL = "RECEIVE_VEHICLES_DETAIL";
export const FETCH_VEHICLES_DETAIL_FAIL = "FETCH_VEHICLES_DETAIL_FAIL";

export const REQUEST_CREATE_VEHICLES = "REQUEST_CREATE_VEHICLES";
export const RECEIVE_CREATE_VEHICLES = "RECEIVE_CREATE_VEHICLES";
export const VEHICLES_CREATE_ERROR = "VEHICLES_CREATE_ERROR";

export const REQUEST_DELETE_VEHICLES = "REQUEST_DELETE_VEHICLES";
export const RECEIVE_DELETE_VEHICLES = "RECEIVE_DELETE_VEHICLES";
export const VEHICLES_DELETE_ERROR = "VEHICLES_DELETE_ERROR";

export const REQUEST_UPDATE_VEHICLES = "REQUEST_UPDATE_VEHICLES";
export const RECEIVE_UPDATE_VEHICLES = "RECEIVE_UPDATE_VEHICLES";
export const VEHICLES_UPDATE_ERROR = "VEHICLES_UPDATE_ERROR";

export const APPLICATIONS_GENERAL_TAB = "General";
export const APPLICATIONS_LOANS_TAB = "Loans";
export const APPLICATIONS_PAYMENTS_TAB = "Payments";
