/* Fetch user details */
export const REQUEST_USER_DETAIL = "REQUEST_USER_DETAIL";
export const RECEIVE_USER_DETAIL = "RECEIVE_USER_DETAIL";
export const FETCH_USER_DETAIL_FAIL = "FETCH_USER_DETAIL_FAIL";

export const REQUEST_CREATE_USER = "REQUEST_CREATE_USER";
export const RECEIVE_CREATE_USER = "RECEIVE_CREATE_USER";
export const USER_CREATE_ERROR = "USER_CREATE_ERROR";

export const REQUEST_DELETE_PRODUCT_RELATION =
  "REQUEST_DELETE_PRODUCT_RELATION";
export const RECEIVE_DELETE_PRODUCT_RELATION =
  "RECEIVE_DELETE_PRODUCT_RELATION";
export const PRODUCT_RELATION_DELETE_ERROR = "PRODUCT_RELATION_DELETE_ERROR";

export const REQUEST_DELETE_USER = "REQUEST_DELETE_USER";
export const RECEIVE_DELETE_USER = "RECEIVE_DELETE_USER";
export const USER_DELETE_ERROR = "USER_DELETE_ERROR";

export const REQUEST_UPDATE_USER = "REQUEST_UPDATE_USER";
export const RECEIVE_UPDATE_USER = "RECEIVE_UPDATE_USER";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";

export const SETTINGS_USER_LOGO = "user_logo_image";
